version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"

#  zookeeper:
#    image: quay.io/debezium/zookeeper
#    ports:
#     - 2181:2181
#     - 2888:2888
#     - 3888:3888
#  kafka:
#    image: quay.io/debezium/kafka
#    ports:
#     - 9092:9092
#    links:
#     - zookeeper
#    environment:
#     - ZOOKEEPER_CONNECT=zookeeper:2181
#  postgres:
#    image: quay.io/debezium/example-postgres
#    ports:
#     - 5432:5432
#    environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=postgres
#  connect:
#    image: quay.io/debezium/connect
#    ports:
#     - 8083:8083
#    links:
#     - kafka
#     - postgres
#    environment:
#     - BOOTSTRAP_SERVERS=kafka:9092
#     - GROUP_ID=1
#     - CONFIG_STORAGE_TOPIC=my_connect_configs
#     - OFFSET_STORAGE_TOPIC=my_connect_offsets
#     - STATUS_STORAGE_TOPIC=my_connect_statuses
    
  my_api:
    build: .
    ports: 
      - '9229:9229'
      - '3000:3000'
    volumes:
      - .:\app
  
