service: Control of Works
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  environment:
    cowenv: dev

functions:
  getUsers:
    name: getUsers
    handler: lambda_funcs/getUsers/index.handler
    events:
      - httpApi:
          path: /getUsers
          method: get

package:
    individually: true

plugins:
  - serverless-offline
