service: Control of Works
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  environment:
    cowenv: dev

functions:
  cow_test:
    name: test_func
    handler: lambda_funcs/test_func/index.handler
    events:
      - httpApi:
          path: /test
          method: get

  mysql:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: false
      convertEmptyValues: true
      noStart: true

package:
    individually: true

plugins:
  - serverless-offline
