service: Control of Works
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  environment:
    cowenv: dev

functions:
  root:
    name: index
    handler: lambda_funcs/root/index.handler
    events:
      - httpApi:
          path: /
          method: get
  getUsers:
    name: getUsers
    handler: lambda_funcs/getUsers/index.handler
    events:
      - httpApi:
          path: /getUsers
          method: get
  postUser:
    name: postUser
    handler: lambda_funcs/postUser/index.handler
    events:
      - httpApi:
          path: /postUser
          method: post
          
package:
    individually: true

plugins:
  - serverless-offline
