service: Control of Works
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  environment:
    cowenv: dev

functions:
  cow_test:
    name: test_func
    handler: lambda_funcs/test_func/index.handler
    events:
      - httpApi:
          path: /test
          method: get

package:
    individually: true

plugins:
  - serverless-offline
