version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
 #     e
 # reporting_db:
 #   image: mysql:5.7
 #   restart: always
 #   environment:
 #     MYSQL_DATABASE: 'db'
 #     MYSQL_USER: 'user'
 #     MYSQL_PASSWORD: 'password'
 #     MYSQL_ROOT_PASSWORD: 'root_password'
 #   ports:
 #     - '3305:3306'
 #   expose:
 #     - '3305'
 #   volumes:
 #     - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"

  zookeeper:
    image: quay.io/debezium/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: quay.io/debezium/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: dhet/debezium-connect
    ports:
     - 8083:8083
    links:
     - kafka
     - db
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - DEBEZIUM_CONFIG_CONNECTOR_CLASS=io.debezium.connector.mysql.MySqlConnector 
     - DEBEZIUM_CONFIG_DATABASE_HOSTNAME=db
     - DEBEZIUM_CONFIG_DATABASE_PORT=3306 
     - DEBEZIUM_CONFIG_DATABASE_PASSWORD=password 
     - DEBEZIUM_CONFIG_DATABASE_USER=user 
     - DEBEZIUM_CONFIG_DATABASE_SERVER_NAME=db 
     - DEBEZIUM_CONFIG_DATABASE_DBNAME=db
  #  volumes:
  #    - ./docker-entrypoint.sh:/docker-entrypoint.sh
  #  entrypoint: sh -c "sh /docker-entrypoint.sh"

# use wait-for-it to add the SQL connector to Debezium
#  execute:
#    links:
#     - connect
#    build: ./docker/debezium_setup
#    environment:
#      - CONNECT_HOST=connect
#      - CONNECT_PORT=8083
        
#  my_api:
#    build: .
#    ports: 
#      - '9229:9229'
#      - '3000:3000'
#    volumes:
#      - .:\app
  
