service: local-api-demo
configValidationMode: off # to allow documentation generation
frameworkVersion: ">=3 <= 3.22.0"
provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs14.x
  
plugins:
  - serverless-openapi
  - serverless-offline

functions:
  root:
    handler: lambda_funcs/root/index.handler
    events:
      - httpApi:
          path: /
          method: get
          documentation:
            summary: Root Endpoint
            description: Used by the API testing framework to ensure live
            requestBody:
              description: An empty request
            requestModels:
              application/json: EmptyGetRequest
            methodResponses:
              - statusCode: 204
                responseBody:
                  description: An empty response
                responseModels:
                  application/json: EmptyGetRequest
              - statusCode: 500
                responseBody:
                  description: An error message indicating a problem with the dockerised server
                responseModels:
                  application/json: ErrorResponse
                  
  getUsers:
    handler: lambda_funcs/getUsers/index.handler
    events:
      - httpApi:
          path: /getUsers
          method: get
          documentation:
            summary: Get User List
            description: Obtain a user list from the application
            requestBody:
              description: An empty request
            requestModels:
              application/json: EmptyGetRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: A list of users
                responseModels:
                  application/json: GetUsersResponse
              - statusCode: 500
                responseBody:
                  description: An error message indicating a problem with the dockerised server
                responseModels:
                  application/json: ErrorResponse

  postUser:
    handler: lambda_funcs/postUser/index.handler
    events:
      - httpApi:
          path: /postUser
          method: post
          documentation:
            summary: Create new User
            description: Create a new user in the application with the provided information
            requestBody:
              description: A PUT request with the user information
            requestModels:
              application/json: CreateUserRequest
            methodResponses:
              - statusCode: 201
                responseBody:
                  description: The created user information returned as JSON
                responseModels:
                  application/json: CreateUserResponse
              - statusCode: 500
                responseBody:
                  description: An error message indicating a problem with the dockerised server
                responseModels:
                  application/json: ErrorResponse
custom:
  defaultStage: dev
  documentation: ${file(serverless.doc.yml):documentation}
