// Mocks generated by Mockito 5.3.2 from annotations
// in user_management/test/features/list_users/data/datasources/user_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:objectbox/src/native/box.dart' as _i5;
import 'package:objectbox/src/native/query/query.dart' as _i2;
import 'package:user_management/core/util/user_mapper.dart' as _i7;
import 'package:user_management/features/list_users/data/models/user_model.dart'
    as _i3;
import 'package:user_management/features/list_users/data/objectbox/entities/user.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQueryBuilder_0<T> extends _i1.SmartFake
    implements _i2.QueryBuilder<T> {
  _FakeQueryBuilder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_2 extends _i1.SmartFake implements _i4.User {
  _FakeUser_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<T> extends _i1.Mock implements _i5.Box<T> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int put(
    T? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
      ) as int);
  @override
  _i6.Future<int> putAsync(
    T? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAsync,
          [object],
          {#mode: mode},
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  int putQueued(
    T? object, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putQueued,
          [object],
          {#mode: mode},
        ),
        returnValue: 0,
      ) as int);
  @override
  List<int> putMany(
    List<T>? objects, {
    _i5.PutMode? mode = _i5.PutMode.put,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putMany,
          [objects],
          {#mode: mode},
        ),
        returnValue: <int>[],
      ) as List<int>);
  @override
  T? get(int? id) => (super.noSuchMethod(Invocation.method(
        #get,
        [id],
      )) as T?);
  @override
  List<T?> getMany(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMany,
          [ids],
          {#growableResult: growableResult},
        ),
        returnValue: <T?>[],
      ) as List<T?>);
  @override
  List<T> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <T>[],
      ) as List<T>);
  @override
  _i2.QueryBuilder<T> query([_i2.Condition<T>? qc]) => (super.noSuchMethod(
        Invocation.method(
          #query,
          [qc],
        ),
        returnValue: _FakeQueryBuilder_0<T>(
          this,
          Invocation.method(
            #query,
            [qc],
          ),
        ),
      ) as _i2.QueryBuilder<T>);
  @override
  int count({int? limit = 0}) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
          {#limit: limit},
        ),
        returnValue: 0,
      ) as int);
  @override
  bool isEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isEmpty,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool contains(int? id) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [id],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool containsMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #containsMany,
          [ids],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool remove(int? id) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [id],
        ),
        returnValue: false,
      ) as bool);
  @override
  int removeMany(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #removeMany,
          [ids],
        ),
        returnValue: 0,
      ) as int);
  @override
  int removeAll() => (super.noSuchMethod(
        Invocation.method(
          #removeAll,
          [],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [IUserMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserMapper extends _i1.Mock implements _i7.IUserMapper {
  MockIUserMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserModel mapUserToUserModel(_i4.User? user) => (super.noSuchMethod(
        Invocation.method(
          #mapUserToUserModel,
          [user],
        ),
        returnValue: _FakeUserModel_1(
          this,
          Invocation.method(
            #mapUserToUserModel,
            [user],
          ),
        ),
      ) as _i3.UserModel);
  @override
  _i4.User mapUserModelToUser(_i3.UserModel? model) => (super.noSuchMethod(
        Invocation.method(
          #mapUserModelToUser,
          [model],
        ),
        returnValue: _FakeUser_2(
          this,
          Invocation.method(
            #mapUserModelToUser,
            [model],
          ),
        ),
      ) as _i4.User);
}
