name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Build out the API and associated database
    - uses: actions/checkout@v3
    - name: Build and run the Docker image
      run: docker-compose up
    # run the integration tests
    
