name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    # Build out the API and associated database
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Build and run the Docker image
      run: docker-compose up -d
      
    # run the integration tests
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
         java-version: '11'
         distribution: 'adopt'
         
    - name: Run integration tests
      run: cd ./testing/backend/integration/integration-tests && mvn test
      
    - name: Publish Surefire Integration Test Reports
      uses: ScaCap/action-surefire-report@v1
      with:
        # surefire/failsafe/junit compatible xml report paths in glob format
        report_paths: ./testing/backend/integration/integration-tests/target/surefire-reports/TEST-*.xml
        # fail run if there were test failures
        fail_on_test_failures: true
        # name of job in build report
        check_name: Integration Test Report
     
    # shutdown
    - name: Shutdown
      run: docker-compose down
