name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    # Build out the API and associated database
    - uses: actions/checkout@v3
    - name: Build and run the Docker image
      run: docker-compose up -d
      
    # run the integration tests
    - name: Set up JDK 11
    - uses: actions/setup-java@v3
      with:
         java-version: '11'
         distribution: 'adopt'
         
    - name: Run integration tests
      run: mvn test
      
    # shutdown
    - name: Shutdown
      run: docker-compose down
