name: Generate and upload API documentation

# no pull_request trigger, the push build combined with the branch lock should be sufficient
on: 
  push:
      paths:
        - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - run: npm install -g
    - run: serverless openapi generate --output documentation/openapi/openapi.yaml --format yaml
    - run: cd docmentation/openapi && redoc-cli build -o index.html openapi.yaml
    - run: cd docmentation/openapi && ls
