name: Generate and upload API documentation

# This pipeline generates API documentation from the serverless definition using serverless-openapi

# no pull_request trigger, the push build combined with the branch lock should be sufficient
on:
  push:
#  push:
#      paths:
#        - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1

    - run: npm config set prefix /usr/local
    - run: npm install -g serverless
    - run: npm install -g serverless-openapi
    - run: npm install -g redoc-cli
    - run: npm install --save-dev
    - run: serverless openapi generate --output documentation/openapi/openapi.yaml --format yaml
    - run: cd documentation/openapi && redoc-cli build -o index.html openapi.yaml
    - run: cd documentation/openapi && ls
    
    - name: Upload GitHub Pages 
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        # Path of the directory containing the static assets.
        path: documentation/openapi/
      
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.2
      with:
        # Name of the artifact to deploy
        artifact_name: documentation/openapi/index.html
      
      
