name: Generate and upload API documentation

# This pipeline generates API documentation from the serverless definition using serverless-openapi

# no pull_request trigger, the push build combined with the branch lock should be sufficient
on: 
  push:
#  push:
#      paths:
#        - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      
    - name: NPM install with caching
      uses: bahmutov/npm-install@v1.6.0
      with:
        # Option to enable or disable use of a lock file (package-lock.json/yarn.lock)
        useLockFile: true
        
    - run: serverless openapi generate --output documentation/openapi/openapi.yaml --format yaml
    - run: cd documentation/openapi && redoc-cli build -o index.html openapi.yaml
    - run: cd documentation/openapi && ls
