# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter FE build, analyse test

# no pull_request trigger, the push build combined with the branch lock should be sufficient
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fe/user_management/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Flutter action
      uses: subosito/flutter-action@v2.8.0
      with:
        flutter-version: 3.3.1
        channel: stable
    - run: flutter pub get
    - run: flutter test --coverage
    # - run: flutter analyze
    # - run: flutter build apk
    
    - name: Very Good Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2.0.0
      with:
        path: fe/user_management/coverage/lcov.info
        min_coverage: 90
