# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter FE build, analyse test

# no pull_request trigger, the push build combined with the branch lock should be sufficient
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fe/user_management/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Flutter action
      uses: subosito/flutter-action@v2.8.0
      with:
        flutter-version: 3.3.1
        channel: stable
    - run: flutter pub get
    - run: flutter test --coverage
    # - run: flutter analyze
    # - run: flutter build apk
    - run: pwd
    - run: ls ./coverage
    - run: cat ./coverage/lcov.info
    
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.10
      with:
        reports: $pwd/coverage/lcov.info
        targetdir: ./coveragereport
    
   # - name: Very Good Coverage
   #   uses: VeryGoodOpenSource/very_good_coverage@v2.0.0
   #   with:
   #     path: ./coverage/lcov.info
