name: Backend Integration Testing

# remove push trigger until FE pipeline dev finished
on: [workflow_dispatch, push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: testing/backend/integration/integration-tests/

    steps:

    # Build out the API and associated database
    - name: checkout
      uses: actions/checkout@v3

    - name: Build and run the Docker image
      run: docker-compose up -d

    # run the integration tests
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
         java-version: '11'
         distribution: 'adopt'

    - name: Run integration tests
      run: mvn test

    - name: Publish Surefire Integration Test Reports
      uses: ScaCap/action-surefire-report@v1
      with:
        # surefire/failsafe/junit compatible xml report paths in glob format
        report_paths: ./target/surefire-reports/TEST-*.xml
        # fail run if there were test failures
        fail_on_test_failures: true
        # name of job in build report
        check_name: Integration Test Report

    # shutdown
    - name: Shutdown
      run: docker-compose down
