name: Lambda Unit Tests

# remove push trigger until FE pipeline dev finished
on: 
   workflow_dispatch:
   push:
      paths:
        - backend/lambda_funcs/**
   pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend/lambda_funcs

    steps:

    # Check out project and run tests
    - name: checkout
      uses: actions/checkout@v3

    - name: Run Jest tests
      run: npm run test
